spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: phumlanidev
    password: Chr1st1@n9432
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect